---
### Deployment: 2つのコンテナと共有ボリュームを定義
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      ### コンテナの定義
      containers:
        ### 1. Nginx
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: git-sync-volume
              mountPath: /usr/share/nginx
        ### 2. git-sync
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.3
          volumeMounts:
            - name: git-sync-volume
              mountPath: /sync
          env:
            ### Gitリポジトリを指定
            - name: GIT_SYNC_REPO
              value: https://github.com/GotoRen/git-sync-example.git
            ### ブランチ名
            - name: GIT_SYNC_BRANCH
              value: master
            - name: GIT_SYNC_ROOT
              value: /sync
            - name: GIT_SYNC_DEST
              value: html
      volumes:
        - name: git-sync-volume
          emptyDir: {}
---
### Service: NodePortを定義して外部へ公開出来るようにする
apiVersion: v1
kind: Service
metadata:
  name: git-sync
  labels:
    app: git-sync
spec:
  selector:
    app: git-sync
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
